# Generated by Django 5.1.7 on 2026-06-20 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('blood_test', 'Blood Test'), ('body_composition', 'Body Composition'), ('cholesterol', 'Cholesterol Panel'), ('thyroid', 'Thyroid Panel'), ('vitamin', 'Vitamin Panel'), ('general', 'General Health Report'), ('other', 'Other')], default='general', max_length=30)),
                ('file', models.FileField(blank=True, null=True, upload_to='health_reports/')),
                ('file_url', models.URLField(blank=True, help_text='Cloudinary URL after upload')),
                ('extracted_text', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_deficiencies', models.JSONField(blank=True, default=list)),
                ('ai_recommendations', models.JSONField(blank=True, default=list)),
                ('ai_risk_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Analysis'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NutritionDeficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrient', models.CharField(max_length=100)),
                ('current_value', models.FloatField(blank=True, null=True)),
                ('recommended_value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(default='mg', max_length=20)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='mild', max_length=10)),
                ('food_sources', models.JSONField(default=list)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deficiencies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
