import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext(null);

const translations = {
  en: {
    // Navbar / Sidebar
    home: "Home",
    dashboard: "Dashboard",
    dietPlan: "Diet Plan",
    foodDb: "Food Database",
    tracking: "Track Progress",
    reports: "Weekly Reports",
    community: "Community",
    dieticians: "Consult Dietician",
    admin: "Admin Panel",
    logout: "Logout",
    login: "Login",
    register: "Register",
    welcome: "Welcome back",

    // Home / Landing
    heroTitle: "Eat Smarter, Live Better",
    heroSubtitle: "Personalized Diet Planning and Wellness Tracking",
    getStarted: "Get Started Now",
    tryCalcs: "Try Free Calculators",
    whyChooseUs: "Why Choose Our Platform?",
    personalPlans: "Personalized Diet Plans",
    personalPlansDesc: "Generate breakfast, lunch, and dinner plans customized to your target weight and active lifestyle.",
    smartTrack: "Smart Hydration & Food Tracker",
    smartTrackDesc: "Log meals and water intake with clean visual charts to hit your daily macro targets.",
    aiConsult: "AI Assistant & Expert Consults",
    aiConsultDesc: "Get instant diet recommendations and chat with our rule-based AI, or book certified dieticians.",

    // Dashboard
    dailySummary: "Daily Summary",
    bmiCalculator: "BMI Calculator",
    bmiCategory: "BMI Category",
    idealWeight: "Ideal Weight Range",
    calorieNeed: "Daily Calories Needed",
    calories: "Calories",
    protein: "Protein",
    carbs: "Carbohydrates",
    fats: "Fats",
    waterTracker: "Hydration Tracker",
    drinkWater: "Log a Glass of Water",
    glasses: "Glasses",
    target: "Target",
    logged: "Logged",
    todayLog: "Today's Logged Meals",
    noMealsLogged: "No meals logged yet today.",
    logMealBtn: "Log a Meal",

    // Tracking
    foodLog: "Food Log",
    waterLog: "Water Log",
    exerciseLog: "Exercise Log",
    weightLog: "Weight Log",
    addFood: "Add Food Entry",
    addExercise: "Add Exercise Entry",
    addWeight: "Log Weight",
    duration: "Duration (mins)",
    caloriesBurned: "Calories Burned",
    weight: "Weight (kg)",
    date: "Date",
    quantity: "Quantity (grams)",
    selectFood: "Select Food Item",
    mealType: "Meal Type",
    save: "Save Entry",
    history: "History",

    // Diet Plan
    generatePlan: "Generate New Diet Plan",
    planName: "Plan Name",
    goal: "Health Goal",
    loseWeight: "Lose Weight",
    maintainWeight: "Maintain Weight",
    gainMuscle: "Gain Muscle / Weight",
    healthyEating: "Healthy Eating Only",
    dietPreference: "Dietary Preference",
    none: "No restrictions",
    vegetarian: "Vegetarian",
    vegan: "Vegan",
    glutenFree: "Gluten-Free",
    diabetic: "Diabetic-Friendly",
    keto: "Ketogenic (Keto)",
    activityLevel: "Activity Level",
    sedentary: "Sedentary (office job)",
    light: "Lightly Active (1-3 days/week)",
    moderate: "Moderately Active (3-5 days/week)",
    active: "Very Active (6-7 days/week)",
    veryActive: "Extra Active (workouts twice a day)",
    createPlanBtn: "Generate My Plan",
    activePlan: "Your Active Diet Plan",
    groceryList: "Auto-Generated Grocery List",
    noPlanYet: "You don't have an active diet plan yet. Generate one above!",

    // Food Database
    searchFood: "Search Foods...",
    foodCategories: "Categories",
    serving: "Serving",
    addCustomFood: "Create Custom Food",
    customFoodName: "Food Name",
    caloriesPer100g: "Calories (per 100g)",
    proteinPer100g: "Protein (g per 100g)",
    carbsPer100g: "Carbs (g per 100g)",
    fatPer100g: "Fat (g per 100g)",
    submit: "Create Food",

    // AI
    aiTitle: "AI Nutrition Tools",
    askAi: "Chat with AI Diet Assistant",
    aiPlaceholder: "Ask me about BMI, water, protein, weight loss, or diet suggestions...",
    send: "Send",
    aiRecipes: "AI Recipe Generator",
    availableIngredients: "Enter Ingredients you have (comma separated)",
    generateRecipeBtn: "Generate Recipe",
    aiRecommendations: "Get AI Meal Recommendation",
    getRecBtn: "Get Smart Recommendation",

    // Reports
    weeklyReport: "Weekly Nutrition Report",
    deficiencyTitle: "Nutrient Deficiency Analysis (Last 7 Days)",
    noDeficiencies: "Excellent! No nutritional deficiencies detected. Keep up the balanced eating!",
    deficiencyWarning: "Warning: You are below the recommended intake for:",
    suggestedFoods: "Suggested foods to add:",
    downloadPdf: "Download PDF Summary",

    // Community
    forumTitle: "Community Forum",
    createPost: "Share a Tip or Recipe",
    postTitle: "Title",
    postContent: "What is on your mind?",
    postCategory: "Category",
    postBtn: "Publish Post",
    comments: "Comments",
    writeComment: "Write a comment...",
    postCommentBtn: "Comment",
    like: "Like",

    // Dieticians
    dieticianBooking: "Book Dietician Appointment",
    experience: "years experience",
    rating: "Rating",
    fee: "Session Fee",
    bookSession: "Book a Session",
    selectDate: "Select Date",
    selectTime: "Select Time",
    notes: "Notes for the dietician",
    confirmBooking: "Confirm Appointment",
    upcomingAppointments: "My Scheduled Appointments",
  },
  hi: {
    // Navbar / Sidebar
    home: "मुख्य पृष्ठ",
    dashboard: "डैशबोर्ड",
    dietPlan: "आहार योजना",
    foodDb: "खाद्य डेटाबेस",
    tracking: "प्रगति ट्रैक करें",
    reports: "साप्ताहिक रिपोर्ट",
    community: "समुदाय",
    dieticians: "आहार विशेषज्ञ से बात करें",
    admin: "एडमिन पैनल",
    logout: "लॉगआउट",
    login: "लॉगिन",
    register: "रजिस्टर",
    welcome: "आपका स्वागत है",

    // Home / Landing
    heroTitle: "आपका व्यक्तिगत आहार योजनाकार",
    heroSubtitle: "एआई संचालित भोजन योजना के साथ अपने स्वास्थ्य लक्ष्यों को प्राप्त करें",
    getStarted: "अभी शुरू करें",
    tryCalcs: "मुफ़्त कैलकुलेटर आज़माएं",
    whyChooseUs: "हमारा मंच क्यों चुनें?",
    personalPlans: "व्यक्तिगत आहार योजनाएं",
    personalPlansDesc: "अपने लक्षित वजन और सक्रिय जीवनशैली के अनुसार अनुकूलित नाश्ता, दोपहर के भोजन और रात के खाने की योजनाएं बनाएं।",
    smartTrack: "स्मार्ट हाइड्रेशन और फूड ट्रैकर",
    smartTrackDesc: "अपने दैनिक मैक्रो लक्ष्यों को पूरा करने के लिए स्पष्ट दृश्य चार्ट के साथ भोजन और पानी का सेवन दर्ज करें।",
    aiConsult: "एआई सहायक और विशेषज्ञ परामर्श",
    aiConsultDesc: "तुरंत आहार सिफारिशें प्राप्त करें और हमारे एआई के साथ चैट करें, या प्रमाणित आहार विशेषज्ञों को बुक करें।",

    // Dashboard
    dailySummary: "दैनिक सारांश",
    bmiCalculator: "बीएमआई कैलकुलेटर",
    bmiCategory: "बीएमआई श्रेणी",
    idealWeight: "आदर्श वजन सीमा",
    calorieNeed: "दैनिक आवश्यक कैलोरी",
    calories: "कैलोरी",
    protein: "प्रोटीन",
    carbs: "कार्बोहाइड्रेट",
    fats: "वसा",
    waterTracker: "हाइड्रेशन ट्रैकर",
    drinkWater: "एक गिलास पानी लॉग करें",
    glasses: "गिलास",
    target: "लक्ष्य",
    logged: "दर्ज किया गया",
    todayLog: "आज का दर्ज भोजन",
    noMealsLogged: "आज अभी तक कोई भोजन दर्ज नहीं किया गया है।",
    logMealBtn: "भोजन दर्ज करें",

    // Tracking
    foodLog: "भोजन लॉग",
    waterLog: "पानी लॉग",
    exerciseLog: "व्यायाम लॉग",
    weightLog: "वजन लॉग",
    addFood: "भोजन प्रविष्टि जोड़ें",
    addExercise: "व्यायाम प्रविष्टि जोड़ें",
    addWeight: "वजन लॉग करें",
    duration: "अवधि (मिनट)",
    caloriesBurned: "कैलोरी बर्न",
    weight: "वजन (किग्रा)",
    date: "तारीख",
    quantity: "मात्रा (ग्राम)",
    selectFood: "खाद्य सामग्री चुनें",
    mealType: "भोजन का प्रकार",
    save: "प्रविष्टि सहेजें",
    history: "इतिहास",

    // Diet Plan
    generatePlan: "नई आहार योजना बनाएं",
    planName: "योजना का नाम",
    goal: "स्वास्थ्य लक्ष्य",
    loseWeight: "वजन घटाएं",
    maintainWeight: "वजन बनाए रखें",
    gainMuscle: "मांसपेशियों का विकास / वजन बढ़ाएं",
    healthyEating: "केवल स्वस्थ भोजन",
    dietPreference: "आहार प्राथमिकता",
    none: "कोई प्रतिबंध नहीं",
    vegetarian: "शाकाहारी",
    vegan: "शाकाहारी (वीगन)",
    glutenFree: "ग्लूटेन-मुक्त",
    diabetic: "मधुमेह-अनुकूल",
    keto: "कीटोजेनिक (कीटो)",
    activityLevel: "गतिविधि स्तर",
    sedentary: "गतिहीन (कार्यालय का काम)",
    light: "हल्का सक्रिय (1-3 दिन/सप्ताह)",
    moderate: "मध्यम सक्रिय (3-5 दिन/सप्ताह)",
    active: "बहुत सक्रिय (6-7 दिन/सप्ताह)",
    veryActive: "अत्यधिक सक्रिय (दिन में दो बार कसरत)",
    createPlanBtn: "मेरी योजना बनाएं",
    activePlan: "आपकी सक्रिय आहार योजना",
    groceryList: "स्वचालित रूप से उत्पन्न किराना सूची",
    noPlanYet: "आपके पास अभी तक कोई सक्रिय आहार योजना नहीं है। ऊपर एक बनाएं!",

    // Food Database
    searchFood: "खाद्य पदार्थ खोजें...",
    foodCategories: "श्रेणियां",
    serving: "सेवारत",
    addCustomFood: "कस्टम भोजन बनाएं",
    customFoodName: "भोजन का नाम",
    caloriesPer100g: "कैलोरी (प्रति 100 ग्राम)",
    proteinPer100g: "प्रोटीन (ग्राम प्रति 100 ग्राम)",
    carbsPer100g: "कार्ब्स (ग्राम प्रति 100 ग्राम)",
    fatPer100g: "वसा (ग्राम प्रति 100 ग्राम)",
    submit: "भोजन बनाएं",

    // AI
    aiTitle: "एआई पोषण उपकरण",
    askAi: "एआई आहार सहायक से चैट करें",
    aiPlaceholder: "मुझसे बीएमआई, पानी, प्रोटीन, वजन घटाने या आहार सुझावों के बारे में पूछें...",
    send: "भेजें",
    aiRecipes: "एआई रेसिपी जेनरेटर",
    availableIngredients: "सामग्री दर्ज करें जो आपके पास हैं (अल्पविराम से अलग)",
    generateRecipeBtn: "रेसिपी उत्पन्न करें",
    aiRecommendations: "एआई भोजन सिफारिश प्राप्त करें",
    getRecBtn: "स्मार्ट सिफारिश प्राप्त करें",

    // Reports
    weeklyReport: "साप्ताहिक पोषण रिपोर्ट",
    deficiencyTitle: "पोषक तत्वों की कमी का विश्लेषण (अंतिम 7 दिन)",
    noDeficiencies: "उत्कृष्ट! कोई पोषण संबंधी कमी नहीं पाई गई। संतुलित खान-पान जारी रखें!",
    deficiencyWarning: "चेतावनी: आप अनुशंसित सेवन से नीचे हैं:",
    suggestedFoods: "जोड़ने के लिए अनुशंसित खाद्य पदार्थ:",
    downloadPdf: "पीडीएफ सारांश डाउनलोड करें",

    // Community
    forumTitle: "सामुदायिक मंच",
    createPost: "कोई सुझाव या रेसिपी साझा करें",
    postTitle: "शीर्षक",
    postContent: "आपके दिमाग में क्या है?",
    postCategory: "श्रेणी",
    postBtn: "पोस्ट प्रकाशित करें",
    comments: "टिप्पणियाँ",
    writeComment: "टिप्पणी लिखें...",
    postCommentBtn: "टिप्पणी करें",
    like: "पसंद करें",

    // Dieticians
    dieticianBooking: "आहार विशेषज्ञ अपॉइंटमेंट बुक करें",
    experience: "वर्षों का अनुभव",
    rating: "रेटिंग",
    fee: "सत्र शुल्क",
    bookSession: "सत्र बुक करें",
    selectDate: "तारीख चुनें",
    selectTime: "समय चुनें",
    notes: "आहार विशेषज्ञ के लिए नोट्स",
    confirmBooking: "अपॉइंटमेंट की पुष्टि करें",
    upcomingAppointments: "मेरे निर्धारित अपॉइंटमेंट",
  },
  es: {
    // Navbar / Sidebar
    home: "Inicio",
    dashboard: "Tablero",
    dietPlan: "Plan de Dieta",
    foodDb: "Base de Alimentos",
    tracking: "Progreso",
    reports: "Reportes Semanales",
    community: "Comunidad",
    dieticians: "Consultar Dietista",
    admin: "Panel de Admin",
    logout: "Cerrar Sesión",
    login: "Iniciar Sesión",
    register: "Registrarse",
    welcome: "Bienvenido de nuevo",

    // Home / Landing
    heroTitle: "Tu Planificador de Dieta Personalizado",
    heroSubtitle: "Logra tus objetivos de salud con la planificación de comidas impulsada por IA",
    getStarted: "Comenzar Ahora",
    tryCalcs: "Calculadoras Gratuitas",
    whyChooseUs: "¿Por qué elegir nuestra plataforma?",
    personalPlans: "Planes de Dieta Personalizados",
    personalPlansDesc: "Genera planes de desayuno, almuerzo y cena personalizados para tu peso objetivo y estilo de vida activo.",
    smartTrack: "Seguimiento Inteligente de Hidratación y Alimentos",
    smartTrackDesc: "Registra comidas y consumo de agua con gráficos visuales limpios para alcanzar tus objetivos macro diarios.",
    aiConsult: "Asistente de IA y Consultas de Expertos",
    aiConsultDesc: "Obtén recomendaciones de dieta instantáneas y chatea con nuestra IA, o reserva dietistas certificados.",

    // Dashboard
    dailySummary: "Resumen Diario",
    bmiCalculator: "Calculadora de IMC",
    bmiCategory: "Categoría de IMC",
    idealWeight: "Rango de Peso Ideal",
    calorieNeed: "Calorías Diarias Necesarias",
    calories: "Calorías",
    protein: "Proteína",
    carbs: "Carbohidratos",
    fats: "Grasas",
    waterTracker: "Control de Hidratación",
    drinkWater: "Registrar un Vaso de Agua",
    glasses: "Vasos",
    target: "Objetivo",
    logged: "Registrado",
    todayLog: "Comidas Registradas Hoy",
    noMealsLogged: "No hay comidas registradas hoy.",
    logMealBtn: "Registrar Comida",

    // Tracking
    foodLog: "Registro de Alimentos",
    waterLog: "Registro de Agua",
    exerciseLog: "Registro de Ejercicio",
    weightLog: "Registro de Peso",
    addFood: "Agregar Entrada de Alimento",
    addExercise: "Agregar Entrada de Ejercicio",
    addWeight: "Registrar Peso",
    duration: "Duración (min)",
    caloriesBurned: "Calorías Quemadas",
    weight: "Peso (kg)",
    date: "Fecha",
    quantity: "Cantidad (gramos)",
    selectFood: "Seleccionar Alimento",
    mealType: "Tipo de Comida",
    save: "Guardar Entrada",
    history: "Historial",

    // Diet Plan
    generatePlan: "Generar Nuevo Plan de Dieta",
    planName: "Nombre del Plan",
    goal: "Objetivo de Salud",
    loseWeight: "Perder Peso",
    maintainWeight: "Mantener Peso",
    gainMuscle: "Ganar Músculo / Peso",
    healthyEating: "Alimentación Saludable",
    dietPreference: "Preferencia Alimentaria",
    none: "Sin restricciones",
    vegetarian: "Vegetariano",
    vegan: "Vegano",
    glutenFree: "Sin Gluten",
    diabetic: "Apto para Diabéticos",
    keto: "Cetogénico (Keto)",
    activityLevel: "Nivel de Actividad",
    sedentary: "Sedentario (trabajo de oficina)",
    light: "Ligeramente Activo (1-3 días/semana)",
    moderate: "Moderadamente Activo (3-5 días/semana)",
    active: "Muy Activo (6-7 días/semana)",
    veryActive: "Extra Activo (doble entrenamiento)",
    createPlanBtn: "Generar Mi Plan",
    activePlan: "Tu Plan de Dieta Activo",
    groceryList: "Lista de Compras Automática",
    noPlanYet: "Aún no tienes un plan de dieta activo. ¡Genera uno arriba!",

    // Food Database
    searchFood: "Buscar Alimentos...",
    foodCategories: "Categorías",
    serving: "Porción",
    addCustomFood: "Crear Alimento Personalizado",
    customFoodName: "Nombre del Alimento",
    caloriesPer100g: "Calorías (por 100g)",
    proteinPer100g: "Proteína (g por 100g)",
    carbsPer100g: "Carbohidratos (g por 100g)",
    fatPer100g: "Grasa (g por 100g)",
    submit: "Crear Alimento",

    // AI
    aiTitle: "Herramientas de IA Nutricionales",
    askAi: "Chatea con Asistente de IA",
    aiPlaceholder: "Pregúntame sobre IMC, agua, proteínas, pérdida de peso...",
    send: "Enviar",
    aiRecipes: "Generador de Recetas de IA",
    availableIngredients: "Ingredientes que tienes (separados por comas)",
    generateRecipeBtn: "Generar Receta",
    aiRecommendations: "Recomendación de Alimentos de IA",
    getRecBtn: "Obtener Recomendación",

    // Reports
    weeklyReport: "Informe de Nutrición Semanal",
    deficiencyTitle: "Análisis de Deficiencia de Nutrientes (Últimos 7 Días)",
    noDeficiencies: "¡Excelente! No se detectaron deficiencias nutricionales.",
    deficiencyWarning: "Advertencia: Estás por debajo de la ingesta recomendada de:",
    suggestedFoods: "Alimentos sugeridos para agregar:",
    downloadPdf: "Descargar Resumen PDF",

    // Community
    forumTitle: "Foro Comunitario",
    createPost: "Comparte un Consejo o Receta",
    postTitle: "Título",
    postContent: "¿Qué tienes en mente?",
    postCategory: "Categoría",
    postBtn: "Publicar Entrada",
    comments: "Comentarios",
    writeComment: "Escribe un comentario...",
    postCommentBtn: "Comentar",
    like: "Me gusta",

    // Dieticians
    dieticianBooking: "Reservar Cita con Dietista",
    experience: "años de experiencia",
    rating: "Calificación",
    fee: "Costo de Sesión",
    bookSession: "Reservar una Sesión",
    selectDate: "Seleccionar Fecha",
    selectTime: "Seleccionar Hora",
    notes: "Notas para el dietista",
    confirmBooking: "Confirmar Cita",
    upcomingAppointments: "Mis Citas Programadas",
  },
  fr: {
    // Navbar / Sidebar
    home: "Accueil",
    dashboard: "Tableau de Bord",
    dietPlan: "Programme Alimentaire",
    foodDb: "Base de Données Aliments",
    tracking: "Suivi des Progrès",
    reports: "Rapports Hebdomadaires",
    community: "Communauté",
    dieticians: "Consulter un Diététicien",
    admin: "Panneau Admin",
    logout: "Se Déconnecter",
    login: "Se Connecter",
    register: "S'inscrire",
    welcome: "Bon retour",

    // Home / Landing
    heroTitle: "Votre Planificateur Alimentaire Personnalisé",
    heroSubtitle: "Atteignez vos objectifs de santé grâce à la planification de repas propulsée par l'IA",
    getStarted: "Commencer Maintenant",
    tryCalcs: "Calculateurs Gratuits",
    whyChooseUs: "Pourquoi choisir notre plateforme ?",
    personalPlans: "Programmes Alimentaires Personnalisés",
    personalPlansDesc: "Générez des plans pour le petit-déjeuner, le déjeuner et le dîner adaptés à votre poids cible et à votre style de vie actif.",
    smartTrack: "Suivi Intelligent de l'Hydratation et des Aliments",
    smartTrackDesc: "Enregistrez vos repas et votre consommation d'eau avec des graphiques visuels clairs pour atteindre vos objectifs quotidiens.",
    aiConsult: "Assistant IA et Consultations d'Experts",
    aiConsultDesc: "Obtenez des recommandations instantanées et discutez avec notre IA, ou réservez un créneau avec nos diététiciens.",

    // Dashboard
    dailySummary: "Résumé Quotidien",
    bmiCalculator: "Calculateur d'IMC",
    bmiCategory: "Catégorie d'IMC",
    idealWeight: "Poids Idéal",
    calorieNeed: "Calories Quotidiennes Requises",
    calories: "Calories",
    protein: "Protéines",
    carbs: "Glucides",
    fats: "Lipides",
    waterTracker: "Suivi d'Hydratation",
    drinkWater: "Enregistrer un Verre d'Eau",
    glasses: "Verres",
    target: "Cible",
    logged: "Enregistré",
    todayLog: "Repas Enregistrés Aujourd'hui",
    noMealsLogged: "Aucun repas enregistré aujourd'hui.",
    logMealBtn: "Enregistrer un Repas",

    // Tracking
    foodLog: "Journal des Aliments",
    waterLog: "Journal de l'Eau",
    exerciseLog: "Journal des Exercices",
    weightLog: "Journal de Poids",
    addFood: "Ajouter un Aliment",
    addExercise: "Ajouter un Exercice",
    addWeight: "Enregistrer le Poids",
    duration: "Durée (mins)",
    caloriesBurned: "Calories Brûlées",
    weight: "Poids (kg)",
    date: "Date",
    quantity: "Quantité (grammes)",
    selectFood: "Sélectionner un Aliment",
    mealType: "Type de Repas",
    save: "Enregistrer l'Entrée",
    history: "Historique",

    // Diet Plan
    generatePlan: "Créer un Programme Alimentaire",
    planName: "Nom du Programme",
    goal: "Objectif de Santé",
    loseWeight: "Perdre du Poids",
    maintainWeight: "Maintenir le Poids",
    gainMuscle: "Prendre du Muscle / Poids",
    healthyEating: "Manger Sainement",
    dietPreference: "Préférence Alimentaire",
    none: "Sans restrictions",
    vegetarian: "Végétarien",
    vegan: "Végétalien (Végan)",
    glutenFree: "Sans Gluten",
    diabetic: "Apto Diabétique",
    keto: "Cétogène (Keto)",
    activityLevel: "Niveau d'Activité",
    sedentary: "Sédentaire (travail de bureau)",
    light: "Légèrement Actif (1-3 jours/semaine)",
    moderate: "Modérément Actif (3-5 jours/semaine)",
    active: "Très Actif (6-7 jours/semaine)",
    veryActive: "Extra Actif (double entraînement quotidien)",
    createPlanBtn: "Générer Mon Programme",
    activePlan: "Votre Programme Actif",
    groceryList: "Liste de Courses Automatique",
    noPlanYet: "Vous n'avez pas encore de programme actif. Générez-en un ci-dessus !",

    // Food Database
    searchFood: "Rechercher des Aliments...",
    foodCategories: "Catégories",
    serving: "Portion",
    addCustomFood: "Créer un Aliment Personnalisé",
    customFoodName: "Nom de l'Aliment",
    caloriesPer100g: "Calories (pour 100g)",
    proteinPer100g: "Protéines (g pour 100g)",
    carbsPer100g: "Glucides (g pour 100g)",
    fatPer100g: "Lipides (g pour 100g)",
    submit: "Créer l'Aliment",

    // AI
    aiTitle: "Outils de Nutrition IA",
    askAi: "Discuter avec l'Assistant IA",
    aiPlaceholder: "Posez-moi des questions sur l'IMC, l'eau, les protéines...",
    send: "Envoyer",
    aiRecipes: "Générateur de Recettes IA",
    availableIngredients: "Ingrédients disponibles (séparés par des virgules)",
    generateRecipeBtn: "Générer Recette",
    aiRecommendations: "Recommandations IA",
    getRecBtn: "Recommander",

    // Reports
    weeklyReport: "Rapport Nutritionnel Hebdomadaire",
    deficiencyTitle: "Analyse des Carences (7 Derniers Jours)",
    noDeficiencies: "Excellent ! Aucune carence nutritionnelle détectée.",
    deficiencyWarning: "Attention : Vous êtes en dessous des apports recommandés pour :",
    suggestedFoods: "Aliments suggérés à ajouter :",
    downloadPdf: "Télécharger le PDF",

    // Community
    forumTitle: "Forum de la Communauté",
    createPost: "Partager une Astuce ou Recette",
    postTitle: "Titre",
    postContent: "Qu'avez-vous en tête ?",
    postCategory: "Catégorie",
    postBtn: "Publier",
    comments: "Commentaires",
    writeComment: "Écrire un commentaire...",
    postCommentBtn: "Commenter",
    like: "J'aime",

    // Dieticians
    dieticianBooking: "Prendre RDV avec un Diététicien",
    experience: "ans d'expérience",
    rating: "Note",
    fee: "Frais de Séance",
    bookSession: "Réserver",
    selectDate: "Choisir Date",
    selectTime: "Choisir Heure",
    notes: "Notes pour le diététicien",
    confirmBooking: "Confirmer RDV",
    upcomingAppointments: "Mes Rendez-vous Prévus",
  },
  de: {
    // Navbar / Sidebar
    home: "Startseite",
    dashboard: "Dashboard",
    dietPlan: "Ernährungsplan",
    foodDb: "Lebensmittel-Datenbank",
    tracking: "Fortschritt",
    reports: "Wochenberichte",
    community: "Community",
    dieticians: "Ernährungsberater",
    admin: "Admin-Bereich",
    logout: "Abmelden",
    login: "Anmelden",
    register: "Registrieren",
    welcome: "Willkommen zurück",

    // Home / Landing
    heroTitle: "Ihr personalisierter Ernährungsplaner",
    heroSubtitle: "Erreichen Sie Ihre Gesundheitsziele mit KI-gestützter Essensplanung",
    getStarted: "Jetzt Starten",
    tryCalcs: "Kostenlose Rechner",
    whyChooseUs: "Warum unsere Plattform wählen?",
    personalPlans: "Personalisierte Ernährungspläne",
    personalPlansDesc: "Erstelle Pläne für Frühstück, Mittag- und Abendessen, die auf dein Zielgewicht und deinen aktiven Lebensstil abgestimmt sind.",
    smartTrack: "Smarter Wasser- und Food-Tracker",
    smartTrackDesc: "Trage Mahlzeiten und Wasserkonsum mit sauberen Diagrammen ein, um deine täglichen Makroziele zu erreichen.",
    aiConsult: "KI-Assistent & Experten-Beratung",
    aiConsultDesc: "Erhalte sofortige Ernährungsempfehlungen und chatte mit unserer KI, oder buche zertifizierte Berater.",

    // Dashboard
    dailySummary: "Tagesübersicht",
    bmiCalculator: "BMI-Rechner",
    bmiCategory: "BMI-Kategorie",
    idealWeight: "Idealgewicht-Bereich",
    calorieNeed: "Täglicher Kalorienbedarf",
    calories: "Kalorien",
    protein: "Eiweiß",
    carbs: "Kohlenhydrate",
    fats: "Fette",
    waterTracker: "Flüssigkeits-Tracker",
    drinkWater: "Ein Glas Wasser eintragen",
    glasses: "Gläser",
    target: "Ziel",
    logged: "Eingetragen",
    todayLog: "Heute eingetragene Mahlzeiten",
    noMealsLogged: "Heute noch keine Mahlzeiten eingetragen.",
    logMealBtn: "Mahlzeit eintragen",

    // Tracking
    foodLog: "Ernährungs-Tagebuch",
    waterLog: "Wasser-Tagebuch",
    exerciseLog: "Sport-Tagebuch",
    weightLog: "Gewichts-Tagebuch",
    addFood: "Essen hinzufügen",
    addExercise: "Aktivität hinzufügen",
    addWeight: "Gewicht eintragen",
    duration: "Dauer (Minuten)",
    caloriesBurned: "Verbrannte Kalorien",
    weight: "Gewicht (kg)",
    date: "Datum",
    quantity: "Menge (Gramm)",
    selectFood: "Lebensmittel auswählen",
    mealType: "Mahlzeit-Typ",
    save: "Eintrag speichern",
    history: "Verlauf",

    // Diet Plan
    generatePlan: "Neuen Ernährungsplan erstellen",
    planName: "Name des Plans",
    goal: "Gesundheitsziel",
    loseWeight: "Gewicht verlieren",
    maintainWeight: "Gewicht halten",
    gainMuscle: "Muskelaufbau / Zunehmen",
    healthyEating: "Nur gesunde Ernährung",
    dietPreference: "Ernährungsweise",
    none: "Keine Einschränkungen",
    vegetarian: "Vegetarisch",
    vegan: "Vegan",
    glutenFree: "Glutenfrei",
    diabetic: "Diabetikerfreundlich",
    keto: "Ketogen (Keto)",
    activityLevel: "Aktivitätslevel",
    sedentary: "Sitzend (Bürojob)",
    light: "Leicht aktiv (1-3 Tage/Woche)",
    moderate: "Mäßig aktiv (3-5 Tage/Woche)",
    active: "Sehr aktiv (6-7 Tage/Woche)",
    veryActive: "Besonders aktiv (zweimal täglich Training)",
    createPlanBtn: "Ernährungsplan erstellen",
    activePlan: "Dein aktiver Ernährungsplan",
    groceryList: "Automatische Einkaufsliste",
    noPlanYet: "Du hast noch keinen aktiven Ernährungsplan. Erstelle oben einen!",

    // Food Database
    searchFood: "Lebensmittel suchen...",
    foodCategories: "Kategorien",
    serving: "Portion",
    addCustomFood: "Eigenes Lebensmittel erstellen",
    customFoodName: "Name des Lebensmittels",
    caloriesPer100g: "Kalorien (pro 100g)",
    proteinPer100g: "Eiweiß (g pro 100g)",
    carbsPer100g: "Kohlenhydrate (g pro 100g)",
    fatPer100g: "Fett (g pro 100g)",
    submit: "Lebensmittel erstellen",

    // AI
    aiTitle: "KI-Ernährungstools",
    askAi: "Mit KI-Assistent chatten",
    aiPlaceholder: "Frage mich nach BMI, Wasser, Eiweiß, Gewichtsverlust...",
    send: "Senden",
    aiRecipes: "KI-Rezept-Generator",
    availableIngredients: "Verfügbare Zutaten (kommagetrennt)",
    generateRecipeBtn: "Rezept generieren",
    aiRecommendations: "KI-Mahlzeitenempfehlung",
    getRecBtn: "Empfehlung erhalten",

    // Reports
    weeklyReport: "Wöchentlicher Ernährungsbericht",
    deficiencyTitle: "Nährstoffmangel-Analyse (Letzte 7 Tage)",
    noDeficiencies: "Hervorragend! Keine Nährstoffmängel festgestellt.",
    deficiencyWarning: "Warnung: Du bist unter der empfohlenen Zufuhr für:",
    suggestedFoods: "Empfohlene Lebensmittel zum Hinzufügen:",
    downloadPdf: "PDF-Zusammenfassung herunterladen",

    // Community
    forumTitle: "Community-Forum",
    createPost: "Beitrag verfassen",
    postTitle: "Titel",
    postContent: "Was beschäftigt dich?",
    postCategory: "Kategorie",
    postBtn: "Veröffentlichen",
    comments: "Kommentare",
    writeComment: "Kommentar schreiben...",
    postCommentBtn: "Kommentieren",
    like: "Gefällt mir",

    // Dieticians
    dieticianBooking: "Termin beim Ernährungsberater buchen",
    experience: "Jahre Erfahrung",
    rating: "Bewertung",
    fee: "Gebühr pro Sitzung",
    bookSession: "Sitzung buchen",
    selectDate: "Datum auswählen",
    selectTime: "Uhrzeit auswählen",
    notes: "Notizen für den Berater",
    confirmBooking: "Buchung bestätigen",
    upcomingAppointments: "Meine gebuchten Termine",
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(localStorage.getItem('lang') || 'en');

  const t = (key) => {
    return (translations[lang] && translations[lang][key]) || (translations['en'] && translations['en'][key]) || key;
  };

  const changeLanguage = (newLang) => {
    setLang(newLang);
    localStorage.setItem('lang', newLang);
  };

  const toggleLanguage = () => {
    const nextLang = lang === 'en' ? 'hi' : 'en';
    changeLanguage(nextLang);
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLanguage, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
