# Generated by Django 6.0.6 on 2026-06-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='diet_preference',
            field=models.CharField(choices=[('none', 'No Preference'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('gluten_free', 'Gluten-Free'), ('diabetic', 'Diabetic-Friendly'), ('keto', 'Ketogenic')], default='none', max_length=20),
        ),
    ]
