# Generated by Django 6.0.6 on 2026-06-11 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(default='🍽️', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Food Categories',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('serving_size_g', models.FloatField(default=100, help_text='Serving size in grams')),
                ('serving_description', models.CharField(default='100g', help_text='e.g. 1 cup, 1 piece', max_length=100)),
                ('calories', models.FloatField(default=0)),
                ('protein_g', models.FloatField(default=0)),
                ('carbs_g', models.FloatField(default=0)),
                ('fat_g', models.FloatField(default=0)),
                ('fiber_g', models.FloatField(default=0)),
                ('sugar_g', models.FloatField(default=0)),
                ('vitamin_c_mg', models.FloatField(default=0)),
                ('vitamin_a_iu', models.FloatField(default=0)),
                ('calcium_mg', models.FloatField(default=0)),
                ('iron_mg', models.FloatField(default=0)),
                ('potassium_mg', models.FloatField(default=0)),
                ('sodium_mg', models.FloatField(default=0)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('is_gluten_free', models.BooleanField(default=False)),
                ('is_diabetic_friendly', models.BooleanField(default=False)),
                ('is_keto', models.BooleanField(default=False)),
                ('cost_inr', models.FloatField(default=10)),
                ('is_custom', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_foods', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to='food.foodcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
